
.\"
.TH BOUND 1 "February,2011" "" "man page"
.SH NAME
bound \- Find boundary numbers in files or STDIN.
.SH SYNOPSIS
\&\fBbound\fR [\-l] <\s-1FILE\s0>
.PP
| \fBbound\fR [\-l]     (Input on \s-1STDIN\s0 from pipeline.)
.PP
\&\fBbound\fR [\-]       (Input on \s-1STDIN\s0.  Use Ctrl-D to stop.)
.SH DESCRIPTION
.B bound
is a program that is part of the numeric utilities package.
.B bound 
will find boundary numbers (minimum and maximum) in files or STDIN. By default it 
will find the upper bound in the set of numbers (the maximum number) in the files or on STDIN. 
You can use the 
.I -l 
option for finding the lower bound (minumum number).
.SH OPTIONS
.TP
.B \-l
-- Return the lower bound number in the set  (the minimum number)
.SH SEE ALSO
\&\fBaverage\fR\|(1), \fBbound\fR\|(1), \fBinterval\fR\|(1), \fBnormalize\fR\|(1), \fBprocess\fR\|(1), \fBsum\fR\|(1), \fBrandom\fR\|(1), \fBrange\fR\|(1), \fBround\fR\|(1)

