.\"
.TH NUMAVERAGE 1 "April,2011" "" "man page"
.SH "NAME"
numaverage \- Find the average of a set of numbers.
.SH "SYNOPSIS"
\fBnumaverage\fR [\-hiIlmM] <\s-1FILE\s0>
.PP
| \fBnumaverage\fR [\-hiIlmM] (Input on \s-1STDIN\s0 from pipeline.)
.PP
\fBnumaverage\fR [\-hiIlmM] (Input on \s-1STDIN\s0. Use Ctrl-D to stop.)
.SH "DESCRIPTION"
By default 
\fBnumaverage\fR will determine the average from all numbers on input. Other options allow you to find the mode and median.
.SH "OPTIONS"
.TP
.B -i
Only return the integer portion of the final sum.
.TP
.B -I
Only return the decimal portion of the final sum
.TP
.B -m
Find the mode (most occuring) of the list of numbers, or when there are more than one mode, the first completed mode.
.TP
.B -M
Find the median (middle number) of the list of numbers.
.TP
.B -l
When finding the median and the count of numbers in the set is even, use the lower middle number instead of the upper middle number.
.TP
.B -h
Help: You are looking at it.
.SH "AUTHORS"
.PP
Edern Hotte (edern.hotte@telecom-bretagne.eu)
.PP
Flavien Moullec (flavien.moullec@telecom-bretagne.eu)
.PP
Reuven Benichou (reuven.benichou@telecom-bretagne.eu)
.SH "SEE ALSO"
\fBnumbound\fR\|(1), \fBnumgrep\fR\|(1), \fBnuminterval\fR\|(1), \fBnumnormalize\fR\|(1), \fBnumprocess\fR\|(1), \fBnumrandom\fR\|(1), \fBnumrange\fR\|(1), \fBnumround\fR\|(1), \fBnumsum\fR\|(1)
.SH "THANKS"
This man page is inspirated by the documentation of num-utils (http://suso.suso.org/programs/num-utils/).
