.\"
.TH NUMBOUND 1 "February,2011" "" "man page"
.SH "NAME"
bound \- Find boundary numbers in files or STDIN.
.SH "SYNOPSIS"
\fBnumbound\fR [\-hl] <\s-1FILE\s0>
.PP
| \fBnumbound\fR [\-hl]     (Input on \s-1STDIN\s0 from pipeline.)
.PP
\fBbound\fR [\-hl]       (Input on \s-1STDIN\s0. Use Ctrl-D to stop.)
.SH "DESCRIPTION"
.B numbound
is a program that is part of the numeric utilities package.
.B numbound 
will find boundary numbers (minimum and maximum) in files or STDIN. By default it 
will find the upper bound in the set of numbers (the maximum number) in the files or on STDIN. 
You can use the 
.I -l 
option for finding the lower bound (minumum number).
.SH "OPTIONS"
.TP
.B -l
Return the lower bound number in the set (the minimum number).
.TP
.B -h
Help: You are looking at it.
.SH "AUTHORS"
.PP
Edern Hotte (edern.hotte@telecom-bretagne.eu)
.PP
Flavien Moullec (flavien.moullec@telecom-bretagne.eu)
.PP
Reuven Benichou (reuven.benichou@telecom-bretagne.eu)
.SH "SEE ALSO"
\fBnumaverage\fR\|(1), \fBnumgrep\fR\|(1), \fBnuminterval\fR\|(1), \fBnumnormalize\fR\|(1), \fBnumprocess\fR\|(1), \fBnumrandom\fR\|(1), \fBnumrange\fR\|(1), \fBnumround\fR\|(1), \fBnumsum\fR\|(1)
.SH "THANKS"
This man page is inspirated by the documentation of num-utils (http://suso.suso.org/programs/num-utils/).

