.IX Title "NUMPROCESS 1"
.TH NUMPROCESS 1 "April,2011" "" "man page"
.SH "NAME"
numprocess \- This program mutates numbers as it encounters them.
.SH "SYNOPSIS"
.IX Header "SYNOPSIS"
\fBnumprocess\fR [\-h] /<expression>/ [\s-1FILE\s0 or \s-1STDIN\s0]
.PP
| \fBnumprocess\fR [\-h] /<expression>/ (Input on \s-1STDIN\s0 from pipeline.)
.PP
\fBnumprocess\fR [\-h] /<expression>/ (Input on \s-1STDIN\s0. Use Ctrl-D to stop.)
.SH "DESCRIPTION"
.IX Header "DESCRIPTION"
\fBnumprocess\fR
will take as one argument, a list of operations to be performed on numbers that it
encounters.  It will perform those operations on each number and return the result in place
of the original number.
.SH "USAGE EXAMPLES"

.PP
Add 1 to all numbers : $ numprocess /+1/ file1
.PP
Convert all numbers from miles to kilometers. Multiply by 8 and divide by 5 : $ cat file1 | numprocess /*8,%5/
.PP
Convert from celcius to fahreheit degrees. Multiply by 9, divide by 5 and add 32 : $ numprocess /*9,%5,+32/ temperatures
.PP
Find the area of each circle from the given radius : $ numprocess /^2,*pi/ radii
.SH "KEYWORDS AND OPERATORS"
For operators, the modifying number goes directly after the operator, with the exception of functions like sqrt, sin, cos, etc.
.PP
.B + 
Addition
.PP
.B -
Subtraction
.PP
.B *
Multiplication
.PP
.B %
Division
.PP
.B ^
Power function
.PP
.B sqrt
Square Root  (*)
.PP
.B sin
Sinus function
.PP
.B cos
Cosinus function
.PP
Constants and keywords that can be used :

.B pi
3.141592654
.PP
.B e
2.718281828
.PP
(*) When using the sqrt operation on negative numbers, it will take the absolute value of the number, sqrt it and then tack an i on the end of the result to signify that the resulting number is imaginary.
.SH "OPTIONS"
.TP
.B -h
Help: You are looking at it.
.SH "AUTHORS"
.PP
Edern Hotte (edern.hotte@telecom-bretagne.eu)
.PP
Flavien Moullec (flavien.moullec@telecom-bretagne.eu)
.PP
Reuven Benichou (reuven.benichou@telecom-bretagne.eu)
.SH "SEE ALSO"
\fBnumaverage\fR\|(1), \fBnumbound\fR\|(1), \fBnumgrep\fR\|(1), \fBnuminterval\fR\|(1), \fBnumnormalize\fR\|(1), \fBnumrandom\fR\|(1), \fBnumrange\fR\|(1), \fBnumround\fR\|(1), \fBnumsum\fR\|(1)
.SH "THANKS"
This man page is inspirated by the documentation of num-utils (http://suso.suso.org/programs/num-utils/).

