.IX Title "NUMRANGE 1"
.TH NUMRANGE 1 "2April,2011" "" "man page"
.SH "NAME"
numrange \- Print out a range of numbers for use in for loops and such.
.SH "SYNOPSIS"
.IX Header "SYNOPSIS"
\&\fBnumrange\fR [\-dhV] /<expression>/
.SH "DESCRIPTION"
.IX Header "DESCRIPTION"
\&\fBnumrange\fR
will print out a list of numbers based on an expression that you specify.  This
is useful for making a list of numbers for use in for loops and so on.
Ranges are inclusive.
Ranges of
numbers are specified using the .. operator, like this /20..50/, which means all
integers from 20 to 50 inclusive.  More complex expressions can be generated using the commas
and the 'i' increment operator.
.SH "OPTIONS"
.IX Header "OPTIONS"
.Vb 6
\&    \-e <set> Exclude the <set> of numbers from the range output.  <set>
\&       is a set of numbers separated by commas.
\&    \-n <n> Use <n> as the separator between numbers.  By default, it
\&       will use a space.  Use \*(Aq\en\*(Aq or \e\en for a newline character or
\&       use the \-N option.
\&    \-N  Just a quick option for using a newline as the separator.
\&
\&    \-h  Help: You\*(Aqre looking at it.
\&    \-V  Increase verbosity.
\&    \-d  Debug mode.  For developers
.Ve
.SH "EXAMPLES"
.IX Header "EXAMPLES"
.Vb 3
\&   All numbers from 1 to 10.
\&    $ numrange /1..10/
\&    1 2 3 4 5 6 7 8 9 10
\&
\&   From 10 to 1. Counting down.
\&    $ numrange /10..1/
\&    10 9 8 7 6 5 4 3 2 1
\&
\&   From 1 to 10 and from 15 to 20.
\&    $ numrange /1..10,15..20/
\&    1 2 3 4 5 6 7 8 9 10 15 16 17 18 19 20
\&
\&   Even numbers from 0 to 10
\&    $ numrange /0..10i2/
\&    0 2 4 6 8 10
\&
\&   Odd numbers.  Notice the starting number in the range expression.
\&    $ numrange /1..10i2/
\&    1 3 5 7 9
\&
\&   Factors of 3 between 99 and 120.
\&    $ numrange /99..120i3/
\&    99 102 105 108 111 114 117 120
\&
\&   Decimal numbers
\&    $ numrange /1.1..2.5i0.1/
\&    1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9 2 2.1 2.2 2.3 2.4 2.5
\&
\&   And negative numbers too.
\&    $ numrange /1.0..\-2.0i0.3/
\&    1 0.7 0.4 0.1 \-0.2 \-0.5 \-0.8 \-1.1 \-1.4 \-1.7 \-2
\&
\&   You can also pad numbers when you are counting up.  This is
\&   a trick of how the Perl programming language deals with ranges:
\&   
\&    $ numrange /01..15/
\&    01 02 03 04 05 06 07 08 09 10 11 12 13 14 15
.Ve
.SH AUTHOR
.PP
Edern Hotte (edern.hotte@telecom-bretagne.eu)
.PP
Flavien Moullec (flavien.moullec@telecom-bretagne.eu)
.PP
Reuven Benichou (reuven.benichou@telecom-bretagne.eu)
.SH SEE ALSO
\&\fBaverage\fR\|(1), \fBbound\fR\|(1), \fBinterval\fR\|(1), \fBnormalize\fR\|(1), \fBprocess\fR\|(1), \fBsum\fR\|(1), \fBrandom\fR\|(1), \fBrange\fR\|(1), \fBround\fR\|(1)
.SH THANKS
This man page is inspirated by the documentation of num-utils (http://suso.suso.org/programs/num-utils/) 
