.IX Title "NUMROUND 1"
.TH NUMROUND 1 "April,2011" "" "man page" Documentation"
.SH "NAME"
numround \- A program that rounds off numbers it encounters.
.SH "SYNOPSIS"
.IX Header "SYNOPSIS"
\fBnumround\fR [\-cfh] <\s-1FILE\s0>
.PP
| \fBnumround\fR [\-cfh] (Input on \s-1STDIN\s0 from pipeline.)
.PP
\fBnumround\fR [\-cdfhV] (Input on \s-1STDIN\s0. Use Ctrl-D to stop.)
.SH "DESCRIPTION"
.IX Header "DESCRIPTION"
\fBnumround\fR
will simply round decimal numbers to the nearest integer or to a factor of any
number using the \-n option.  You can also force it to round up (ceiling) or
round down(floor) using the \-c and \-f options.
.SH "OPTIONS"
.TP
.B -c
Force the number to be rounded up. Ceiling.
.TP
.B -f
Force the number to be rounded down. Floor.
.TP
.B -n <n>
Round numbers to the nearest factor of <n>.
.TP
.B -h
Help: You are looking at it.

.SH "AUTHORS"
.PP
Edern Hotte (edern.hotte@telecom-bretagne.eu)
.PP
Flavien Moullec (flavien.moullec@telecom-bretagne.eu)
.PP
Reuven Benichou (reuven.benichou@telecom-bretagne.eu)
.SH "SEE ALSO"
\fBnumaverage\fR\|(1), \fBnumbound\fR\|(1), \fBnumgrep\fR\|(1), \fBnuminterval\fR\|(1), \fBnumnormalize\fR\|(1), \fBnumprocess\fR\|(1), \fBnumrandom\fR\|(1), \fBnumrange\fR\|(1), \fBnumsum\fR\|(1)
.SH "THANKS"
This man page is inspirated by the documentation of num-utils (http://suso.suso.org/programs/num-utils/).
